---

- name: install mariadb
  apt:
    pkg:
      - 'mariadb-server'
      - 'python-pymysql'

- name: create mariadb configuration file
  template: src=99-openstack.cnf dest=/etc/mysql/mariadb.conf.d/99-openstack.cnf

- name: restart mariadb
  service: name=mysql state=restarted

# TODO:mysql_secure_installation

