---

- name: install mariadb
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - mariadb-server
    - python-mysqldb
    - python-pymysql

- name: create mariadb configuration file
  template: src=mysqld_openstack.cnf dest=/etc/mysql/conf.d/mysqld_openstack.cnf
  notify: restart mariadb

# TODO:mysql_secure_installation
