---

- name: edit sysctl conf file
  file: src=sysctl.conf dest=/etc/sysctl.conf

- name: Implement the changes
  command: sysctl -p

- name: install neutron packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - neutron-plugin-ml2
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

- name: edit neutron conf file
  template: src=neutron.conf.j2 dest=/etc/neutron/neutron.conf

- name: edit ml2 conf file
  template: src=ml2_conf.ini.j2 dest=/etc/neutron/plugins/ml2/ml2_conf.ini

- name: edit l3 agent conf file
  template: src=l3_agent.ini.j2 dest=/etc/neutron/l3_agent.ini
  
- name: edit dhcp agent conf file
  template: src=dhcp_agent.ini.j2 dest=/etc/neutron/dhcp_agent.ini

- name: edit metadata agent conf file
  template: src=metadata_agent.ini.j2 dest=/etc/neutron/metadata_agent.ini

- name: Restart the OVS service
  service: name=openvswitch-switch state=restarted

- name: Add the external bridge
  command: ovs-vsctl add-br br-ex

- name: Add a port to the external bridge that connects to the physical external network interface
  command: ovs-vsctl add-port br-ex {{ INTERFACE_NAME }}

- name: Restart the Networking services
  service: name={{ item }} state=restarted
  with_items:
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

