---

- name: create database
  mysql_db: name=cinder state=present

- name: create cinder user
  mysql_user: name=cinder host={{ item }} password={{ CINDER_DBPASS }} priv=cinder.*:ALL state=present
  with_items:
    - 'localhost'
    - "%"

- name: create cinder service entry and endpoint
  script: create_cinder_service_entity_and_api_endpoint.sh {{ CINDER_PASS }} {{ api_host }}
  environment: "{{ admin_openrc }}"
  become: no

- name: install cinder packages
  apt:
    pkg:
    - cinder-api
    - cinder-scheduler

- name: edit cinder conf file
  template: src=cinder.conf.j2 dest=/etc/cinder/cinder.conf

- name: Populate the Cinder database
  script: cinder_db_sync.sh

- name: Restart the Compute API service
  service: name=nova-api state=restarted

- name: Restart the Block Storage services
  service: name={{ item }} state=restarted
  with_items:
    - cinder-scheduler
    - apache2
