---

- name: create database
  mysql_db: name=cinder state=present
  become: yes

- name: create cinder user
  mysql_user: name=cinder host={{ item }} password={{ CINDER_DBPASS }} priv=cinder.*:ALL state=present
  with_items:
    - 'localhost'
    - "%"
  become: yes

- name: create cinder service entry and endpoint
  script: create_cinder_service_entity_and_api_endpoint.sh {{ CINDER_PASS }} {{ api_host }}
  environment: "{{ admin_openrc }}"

- name: install cinder packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - cinder-api
    - cinder-scheduler
  become: yes

- name: edit cinder conf file
  template: src=cinder.conf.j2 dest=/etc/cinder/cinder.conf
  become: yes

- name: Populate the Cinder database
  script: cinder_db_sync.sh
  become: yes

- name: Restart the Compute API service
  service: name=nova-api state=restarted
  become: yes

- name: Restart the Block Storage services
  service: name={{ item }} state=restarted
  with_items:
    - cinder-scheduler
    - apache2
  become: yes
