---

- name: create database
  mysql_db: name=neutron state=present
  
- name: create neutron user
  mysql_user: name=neutron host={{ item }} password={{ NEUTRON_DBPASS }} priv=neutron.*:ALL state=present
  with_items:
    - localhost
    - "%"

- name: create neutron service entry and endpoint
  script: create_neutron_service_entity_and_api_endpoint.sh {{ NEUTRON_PASS }} {{ api_scheme }} {{ api_host }}
  environment: "{{ admin_openrc }}"
  sudo: no

- name: install neutron packages
  apt:
    pkg:
    - neutron-server
    - neutron-plugin-ml2
    - neutron-linuxbridge-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

- name: Configure the server component
  template: src=neutron.conf.j2 dest=/etc/neutron/neutron.conf
  tags: conf

- name: Configure the Modular Layer 2 (ML2) plug-in
  template: src=ml2_conf.ini.j2 dest=/etc/neutron/plugins/ml2/ml2_conf.ini
  tags: conf

- name: Configure the Linux bridge agent
  template: src=linuxbridge_agent.ini.j2 dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini
  tags: conf

- name: Configure the layer-3 agent
  template: src=l3_agent.ini.j2 dest=/etc/neutron/l3_agent.ini
  tags: conf

- name: Configure the DHCP agent
  template: src=dhcp_agent.ini.j2 dest=/etc/neutron/dhcp_agent.ini
  tags: conf

- name: Configure the metadata agent
  template: src=metadata_agent.ini.j2 dest=/etc/neutron/metadata_agent.ini
  tags: conf

- name: Populate the database
  script: neutron_db_sync.sh

- name: Restart the Compute API service and the Networking services
  service: name={{ item }} state=restarted
  with_items:
    - nova-api
    - neutron-server
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
  tags: conf
