DEFAULT:
  rpc_backend: rabbit

oslo_messaging_notifications:
  driver: messagingv2

oslo_messaging_rabbit:
  rabbit_host: "{{ RABBIT_HOST }}"
  rabbit_userid: openstack
  rabbit_password: "{{ RABBIT_PASS }}"
