---

- name: install rabbitmq
  apt: pkg=rabbitmq-server update_cache=yes cache_valid_time=3600

- name: add openstack user
  rabbitmq_user: user=openstack
                 password={{ RABBIT_PASS }}
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
