---

- name: Install the package
  apt: pkg=openstack-dashboard update_cache=yes cache_valid_time=3600

- name: edit local_settings.py file
  template: src=local_settings.py.j2 dest=/etc/openstack-dashboard/local_settings.py

- name: Reload the web server configuration
  service: name=apache2 state=reloaded
