---

- name: Install the MongoDB packages
  apt: name={{ item }}
  with_items:
    - mongodb-server
    - mongodb-clients
    - python-pymongo

- name: Edit /etc/mongodb.conf
  lineinfile: dest=/etc/mongodb.conf line="bind_ip = {{ controller_mgmt_ip }}" regexp="^bind_ip"

- name: Stop MongoDB
  service: name=mongodb state=stopped

- name: Remove initial journal
  command: rm /var/lib/mongodb/journal/prealloc.*
  ignore_errors: yes

- name: Start MongoDB
  service: name=mongodb state=started
