---

- name: install the packages
  apt:
    pkg:
      - 'memcached'
      - 'python-memcache'

- name: edit memcached conf file
  template: src=memcached.conf.j2 dest=/etc/memcached.conf

- name: Restart the Memcached service
  service: name=memcached state=restarted
 
