- hosts: controller
  roles:
    - common
    - ntp_server
    - mariadb
    - rabbitmq
    - memcached
    - etcd
    - keystone
    - glance
    - nova
    - neutron
    - horizon
    - cinder
    - heat
