---

- name: install nova packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - nova-compute
    - sysfsutils

- name: edit nova conf file
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf

- name: Configure libvirt to use QEMU instead of KVM
  lineinfile: dest=/etc/nova/nova-compute.conf
              line="virt_type=qemu" regexp="^virt_type"
  when: virt_type is defined and virt_type == "qemu"

- name: install neutron packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - neutron-plugin-linuxbridge-agent
    - conntrack

- name: edit neutron conf file
  template: src=neutron.conf.j2 dest=/etc/neutron/neutron.conf

- name: Configure the Linux bridge agent
  template: src=linuxbridge_agent.ini.j2 dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini

- name: Restart the Compute service
  service: name=nova-compute state=restarted

- name: Restart the Linux bridge agent
  service: name=neutron-plugin-linuxbridge-agent state=restarted

- name: remove the SQLite database file
  file: path=/var/lib/nova/nova.sqlite state=absent
