---

- name: Install etcd
  apt: name=etcd update_cache=yes cache_valid_time=3600

- name: copy hosts file
  template: src=etcd.j2 dest=/etc/default/etcd

- name: enable and start etcd
  systemd:
    name: etcd
    enabled: yes
    state: started
